mfts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('accounts/', include('allauth.urls')),
]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('who/<int:pk>', views.DetailView.as_view(), name='detail'),
    path('inquiry/', views.InquiryView.as_view(), name='inquiry'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):

    class Meta:
        verbose_name_plural = 'CustomUser'

post/models.py
from django.db import models

# Create your models here.

post/forms.py
from django import forms
from django.core.mail import EmailMessage

class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=25)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length=25)
    message = forms.CharField(label='メッセージ', max_length=150, widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してください。'

        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'
    
    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ: \n{2}'.format(name, email, message)
        from_email = 'admin@example.com'
        to_list = ['test@example.com']
        cc_list = [email]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

accounts/views.py
from django.shortcuts import render

# Create your views here.

post/views.py
import logging
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views import generic
from django.contrib import messages
from .forms import InquiryForm

logger = logging.getLogger(__name__)

class IndexView(generic.TemplateView):
    template_name = "index.html"

class DetailView(generic.DetailView):
    template_name = "detail.html"

class InquiryView(generic.FormView):
    template_name = 'inquiry.html'
    form_class = InquiryForm
    success_url = reverse_lazy('post:inquiry')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました。')
        logger.info(f'お問い合わせをした方のお名前：{form.cleaned_data["name"]}')
        return super().form_valid(form)

post/templates/base.html
{% load static %}

<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scala=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %} {% endblock %}</title>

    <!--Custom fonts for this template-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i">

    <!--Custom styles for this template-->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <!--My style-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %} {% endblock %}
</head>

<body>
    <div id="wrapper">
        <!--Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'post:index' %}">五つ子紹介</a>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link {% block active_inquiry %}{% endblock %}" href="{% url 'post:inquiry' %}">お問い合わせ</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="#">投稿一覧</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="#">検索</a>
                            </li>
                        {% endif %}
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_logout' %}">ログアウト</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_login' %}">ログイン</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_signup' %}">サインイン</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {% block header %} {% endblock %}

        {% if messages %}
        <div class="container">
            <div class="row">
                <div class="my-div-style w-100">
                    <ul class="messages" style="list-style: none;">
                        {% for message in messages %}
                            <li {% if message.tags %} class='text-center {{ message.tags }}' {% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        {% endif %}
        
        {% block contents %} {% endblock %}

        <!--Footer-->
        <footer class="py-5 bg-black">
            <div class="container">
                <p class="m-0 text-center text-white small">Copyright &copy; mfts 2024</p>
            </div>
        </footer>

    </div>
</body>
</html>

post/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %} 五つ子一覧 {% endblock %}

{% block header %}
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container">
            <h1 class="masthead-heading mb-0">五等分の花嫁｜キャラクター紹介</h1>
            <h2 class="mb-0">さてさて、この時を何年待ったでしょうか。待ちに待った五つ子の紹介です！</h2>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block contents %}
<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/一花.jpg' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">中野一花</h2>
                    <p>五つ子の長女、将来は女優になることが夢</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/二乃.jpg' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="p-5">
                    <h2 class="display-4">中野二乃</h2>
                    <p>五つ子の次女、毒舌だが実は家族思い</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/三玖.jpg' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">中野三玖</h2>
                    <p>五つ子の三女、ミステリアスで大人しい</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/四葉.jpg' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="p-5">
                    <h2 class="display-4">中野四葉</h2>
                    <p>五つ子の四女、運動神経抜群だが勉強は一番出来ない</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/五月.jpg' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">中野五月</h2>
                    <p>五つ子の五女、カレー大好きの可愛い真面目ドジ</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

post/templates/inquiry.html
{% extends 'base.html' %}

{% block title %}お問い合わせ{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}" class="col-4 mt-3 mb-3">
                            <strong>{{ field.label_tag }}</strong>
                        </label>
                        <div class="col-8">
                            {{ field }}
                            {{ field.error }}
                        </div>
                    </div>
                {% endfor %}
                <div class="row">
                    <div class="col-4 mx-auto">
                        <button type="submit" class="btn btn-primary mt-3">送信</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}